package com.ros.administration.model.enums;

public enum ERole {
	ROLE_SUPERADMIN,
	ROLE_ACCOUNTOFFICER,
	ROLE_CLIENTADMIN,
	ROLE_OPERATIONALMANAGER,
	ROLE_GENERALMANAGER,
	ROLE_RESTAURANTADMIN,
	ROLE_ASSISTANTMANAGER,
	ROLE_SUPERVISOR,
	ROLE_USER,
	ROLE_FOH,
	ROLE_BOH
}
